applications/workouts/urls.py
# -*- coding: utf-8 -*-
# vim: set expandtab tabstop=4 shiftwidth=4:

from django.conf import settings
from django.conf.urls import url

from .views import *  # nopep8

urlpatterns = [

    url(r'^$', ListWorkoutsView.as_view(), name='index'),

    url(r'^create$', CreateWorkoutView.as_view(), name='create'),

    url(r'^(?P<workout_id>\d+)$', ShowWorkoutView.as_view(), name='show'),

    url(r'^(?P<workout_id>\d+)/add_segment$',
        AddSegmentView.as_view(),
        name='add_segment'),

    url(r'^(?P<workout_id>\d+)/segment/(?P<segment_id>\d+)$',
        ShowSegmentView.as_view(),
        name='show_segment'),

    url(r'^(?P<workout_id>\d+)/segment/(?P<segment_id>\d+)/edit$',
        EditSegmentView.as_view(),
        name='edit_segment'),

]

workoutholic/urls.py
# -*- coding: utf-8 -*-
# vim: set expandtab tabstop=4 shiftwidth=4:

from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView


urlpatterns = [

    url(r'^admin/', admin.site.urls),

    url(r'^$',
        TemplateView.as_view(template_name='workouts/home.html'),
        name='home'),

    url(r'^exercises/',
        include('applications.exercises.urls', namespace='exercises')),

    url(r'^workouts/',
        include('applications.workouts.urls', namespace='workouts')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/segments/detail.html
{% extends "layouts/base.html" %}
{% load static %}
{% load i18n %}

{% block content %}
    <div class="row">
        <div class="col-md-12">

            {{segment}}

            <div class="actions">
                <a class="btn btn-info"
                   href="{{segment.edit_url}}">
                    {% trans "Add Exercises" %}
                </a>
            </div>
        </div>
    </div>
{% endblock content %}

templates/segments/edit.html
{% extends "layouts/base.html" %}
{% load bootstrap3 %}
{% load formset_tags %}
{% load i18n %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <dl>
                <dt>{% trans "Segment" %}</dt>
                <dd>{{segment.workout_type}}</dd>
                <dt>{% trans "Laps" %}</dt>
                <dd>{{segment.laps}}</dd>
            </dl>
            <form action="{% url 'workouts:edit_segment' segment_id=segment.id workout_id=segment.workout.id %}"
                  method="POST"
                  accept-charset="utf-8"
                  enctype="multipart/form-data">

                {% csrf_token %}

                <div data-formset-container data-formset-prefix="{{ formset.prefix }}">
                    {{ formset.management_form }}

                    <div data-formset-body>
                        <!-- New forms will be inserted in here -->
                        {% for field_form in formset %}
                            <div data-formset-form>
                                {% bootstrap_form field_form %}
                            </div>
                        {% endfor %}
                    </div>

                    <script type="form-template" data-formset-empty-form>
{% escapescript %}
   <div data-formset-form>
    {% bootstrap_form formset.empty_form %}
</div>
{% endescapescript %}
                    </script>

                    <!-- This button will add a new form when clicked -->
                    <input type="button" value=" {% trans "add another exercise" %}" data-formset-add class="btn btn-primary">

                    <input type="submit"
                           class="btn btn-success"
                           value="{% trans "create" %}" />
            </form>
                </div>
        </div>
    {% endblock content %}

    {% block extra_js %}
        {{form.media}}
        {{formset.media}}
    {% endblock extra_js %}