applications/workouts/urls.py
# -*- coding: utf-8 -*-
# vim: set expandtab tabstop=4 shiftwidth=4:

from django.conf import settings
from django.conf.urls import url

from .views import *  # nopep8

urlpatterns = [

    url(r'^$', ListWorkoutsView.as_view(), name='index'),

    url(r'^create$', CreateWorkoutView.as_view(), name='create'),

    url(r'^(?P<workout_id>\d+)$', ShowWorkoutView.as_view(), name='show'),

    url(r'^(?P<workout_id>\d+)/add_segment$',
        AddSegmentView.as_view(),
        name='add_segment'),

    url(r'^(?P<workout_id>\d+)/segment/(?P<segment_id>\d+)$',
        ShowSegmentView.as_view(),
        name='show_segment'),

    url(r'^(?P<workout_id>\d+)/segment/(?P<segment_id>\d+)/edit$',
        EditSegmentView.as_view(),
        name='edit_segment'),

]

workoutholic/urls.py
# -*- coding: utf-8 -*-
# vim: set expandtab tabstop=4 shiftwidth=4:

from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView


urlpatterns = [

    url(r'^admin/', admin.site.urls),

    url(r'^$',
        TemplateView.as_view(template_name='workouts/home.html'),
        name='home'),

    url(r'^exercises/',
        include('applications.exercises.urls', namespace='exercises')),

    url(r'^workouts/',
        include('applications.workouts.urls', namespace='workouts')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/components/navbar.html
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home' %}">
                Workoutholic
            </a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a href="#"
                       class="dropdown-toggle"
                       data-toggle="dropdown"
                       role="button"
                       aria-haspopup="true"
                       aria-expanded="false">
                        Exercises <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="{% url 'exercises:index' %}">List</a>
                        </li>
                        <li>
                            <a href="{% url 'exercises:create' %}">New</a>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#"
                       class="dropdown-toggle"
                       data-toggle="dropdown"
                       role="button"
                       aria-haspopup="true"
                       aria-expanded="false">
                        Workouts <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="{% url 'workouts:index' %}">List</a>
                        </li>
                        <li>
                            <a href="{% url 'workouts:create' %}">New</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>